Cloud_testapp with startup script
Otus-DevOps-2021-05/Ilman89_infra pull request #4
Opened 2021-07-31 23:11 UTC by Ilman89

# Выполнено ДЗ № 6

 - [ *] Основное ДЗ
 - [ *] Задание со *

## В процессе сделано:
 - Пункт 1 Deploy приложения
 - Пункт 2 Создание скриптов

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [* ] Выставил label с номером домашнего задания
 - [ *] Выставил label с темой домашнего задания

2021-08-02 16:27 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Вам стоит свериться с методичкой, так же стоит добавить адреса приложения в ридми. ДЗ возвращаю на доработку.

2021-08-02 22:50 UTC, Ilman89 commented
Здравствуйте! Ридми в первый раз почему то не обновился после коммита. Перезалил. Все работает, но ошибки по порту 27017 я не понимаю. Подскажите пожалуйста.

2021-08-03 08:55 UTC, mrgreyves approved these changes
Здравствуйте!) История с портом, это история с монгой, тут момент может быть в том что разнятся версии монги, из-за этого и ошибки. На эту ошибку в принципе можем не обращать внимание, дз принимаю!=)

2021-08-03 13:28 UTC, merged

2021-08-03 13:28 UTC, Ilman89 commented
Спасибо)